from __future__ import annotations

from src.utils.common_config_ee_osm import (
    FEATURE_COLUMNS_EE_OSM,
    FINAL_TARGET_COLUMNS_EE_OSM,
    FORWARD_DATA_PATH_EE_OSM,
    MODELS_DIR_EE_OSM,
    RANDOM_STATE_EE_OSM,
    TEST_SIZE_EE_OSM,
    TRAIN_DATA_PATH_EE_OSM,
    TRAIN_TARGET_COLUMNS_EE_OSM,
    VALIDATION_SIZE_EE_OSM,
)


MODEL_OUTPUT_DIR_EE_OSM = MODELS_DIR_EE_OSM / "mlp_ee_osm"

HIDDEN_LAYER_SIZES_GRID_EE_OSM = [(32,), (64,), (64, 32)]
ACTIVATION_GRID_EE_OSM = ["relu", "tanh"]
ALPHA_GRID_EE_OSM = [0.0001, 0.001, 0.01]
LEARNING_RATE_INIT_GRID_EE_OSM = [0.001, 0.01]
MAX_ITER_GRID_EE_OSM = [300, 500]
