from __future__ import annotations

from src.utils.common_config_ee_osm import (
    FEATURE_COLUMNS_EE_OSM,
    FINAL_TARGET_COLUMNS_EE_OSM,
    FORWARD_DATA_PATH_EE_OSM,
    MODELS_DIR_EE_OSM,
    RANDOM_STATE_EE_OSM,
    TEST_SIZE_EE_OSM,
    TRAIN_DATA_PATH_EE_OSM,
    TRAIN_TARGET_COLUMNS_EE_OSM,
    VALIDATION_SIZE_EE_OSM,
)


MODEL_OUTPUT_DIR_EE_OSM = MODELS_DIR_EE_OSM / "xgboost_ee_osm"

N_ESTIMATORS_GRID_EE_OSM = [100, 200, 300]
MAX_DEPTH_GRID_EE_OSM = [3, 4, 6]
LEARNING_RATE_GRID_EE_OSM = [0.03, 0.05, 0.1]
SUBSAMPLE_GRID_EE_OSM = [0.8, 1.0]
COLSAMPLE_BYTREE_GRID_EE_OSM = [0.8, 1.0]
REG_ALPHA_GRID_EE_OSM = [0.0, 0.1]
REG_LAMBDA_GRID_EE_OSM = [1.0, 3.0]
